[package]
name = "shimmeringmoon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
edit-distance = "2.1.0"
image = "0.25.1"
kd-tree = "0.6.0"
num = "0.4.3"
plotlib = "0.5.1"
poise = "0.6.1"
prettytable-rs = "0.10.0"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio", "chrono"] }
tesseract = "0.15.1"
tokio = {version="1.38.0", features=["rt-multi-thread"]}
typenum = "1.17.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
